[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
wakama_oracle_anchor = "93eL55wjf62Pw8UPsKS8V7b9efk28UyG8C74Vif2gMNR"

[registry]
url = "/home/wakama/.config/solana/wakama-devnet.json"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
